apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    env: monitor
spec:
  containers:
    - name: task-pv-container
      image: httpd:latest
      ports:
        - containerPort: 80
          name: "apache-server"
